# Generated by Django 4.1.2 on 2022-11-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
    ]
